# Auth Service - Cấu hình đơn giản cho người mới học
server:
  port: 8081

spring:
  application:
    name: auth-service
  
  # H2 Database - đơn giản cho học tập
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    
  h2:
    console:
      enabled: true
      path: /h2-console

# Logging đơn giản
logging:
  level:
    com.hung.expensive: INFO
    org.springframework.web: INFO