# Why: YAML format cho better readability và hierarchical configuration
server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    config:
      enabled: false
  
  # Why: Database configuration - separate database cho auth service
  datasource:
    url: jdbc:mysql://localhost:3306/expensive_auth?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  # Why: H2 database cho development và testing
  profiles:
    active: dev

# Why: JWT configuration - centralized trong config server sau này
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24 hours

# Why: Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Why: Logging configuration
logging:
  level:
    com.hung.expensive.auth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Why: Development profile với H2 database
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

---
# Why: Production profile với MySQL
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql-auth:3306/expensive_auth
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
