# Auth Service - Cấu hình MySQL cho production
server:
  port: 8081

spring:
  application:
    name: auth-service
  
  # MySQL Database - Production ready
  datasource:
    url: jdbc:mysql://localhost:3306/expensive_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: expensive_user
    password: expensive_password
    
  jpa:
    hibernate:
      ddl-auto: validate  # Why: Update schema thay vì create-drop để preserve data
    database-platform: org.hibernate.dialect.MySQLDialect  # Why: Updated dialect for MySQL 8+
    show-sql: true  # Why: Show SQL trong development để debug
    properties:
      hibernate:
        format_sql: true  # Why: Format SQL queries để dễ đọc
        use_sql_comments: true  # Why: Show comments trong generated SQL

# Logging đơn giản
logging:
  level:
    com.hung.expensive: INFO
    org.springframework.web: INFO